# Generated by Django 5.2.8 on 2025-12-01 08:48

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_alter_profile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image_profile',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='images/profile/'),
        ),
    ]
