# Generated by Django 5.2.8 on 2025-12-01 15:22

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to=' profiles/images/'),
        ),
    ]
