# Generated by Django 5.2.8 on 2025-12-03 00:20

import sorl.thumbnail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0004_alter_profile_image_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image_profile',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='profiles/images/'),
        ),
    ]
