# Generated by Django 5.2.8 on 2025-11-25 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_rename_text_post_title_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
